name: Build 11ty and css
on:
  push:
    branches:
      - main

# Cancel a previous build if still running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Conditional environmental if's      
env:
  UPDATE_NPM: false # false = deploy, true = update npm

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: env.UPDATE_NPM != 'true'
        run: npm i  # npm update --save
        
      - name: Update dependencies
        if: env.UPDATE_NPM == 'true'
        run: npm update --save
        
      - name: Npm Build
        if: env.UPDATE_NPM != 'true'
        run: npm run build

      - name: Deploy
        if: env.UPDATE_NPM != 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: pull request on npm update
        if: env.UPDATE_NPM == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          add-paths: | # to update the package.json and package-lock.json
            *.json
